title: <span style="font-variant:small-caps;"><font size="6.5em">Seokil Kang</font></span>
logo: /profile.jpg
theme: jekyll-theme-minimal
minimal_mistakes_skin: "air"
author:
  mail: kangseokil@bok.or.kr
  github: seokil-kang
